"""Disable recipient from request

Revision ID: 34ed6dcb35af
Revises: d83fcdc430b4
Create Date: 2021-11-18 18:11:17.808129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34ed6dcb35af'
down_revision = 'd83fcdc430b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('request_ibfk_2', 'request', type_='foreignkey')
    op.drop_column('request', 'recipient')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('recipient', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('request_ibfk_2', 'request', 'employee', ['recipient'], ['id'])
    # ### end Alembic commands ###
