"""empty message

Revision ID: c11560165bc4
Revises: 34ed6dcb35af
Create Date: 2021-11-19 19:27:11.444701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c11560165bc4'
down_revision = '34ed6dcb35af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department', 'salary')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('salary', mysql.DECIMAL(precision=10, scale=0), nullable=False))
    # ### end Alembic commands ###
