"""empty message

Revision ID: d83fcdc430b4
Revises: e6767189564c
Create Date: 2021-11-18 17:35:44.542715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83fcdc430b4'
down_revision = 'e6767189564c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('salary', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'salary')
    # ### end Alembic commands ###
