"""Add request system

Revision ID: e6767189564c
Revises: 7ff5a7d96ad7
Create Date: 2021-11-17 15:25:40.944783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6767189564c'
down_revision = '7ff5a7d96ad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.Integer(), nullable=False),
    sa.Column('recipient', sa.Integer(), nullable=False),
    sa.Column('change_department_id', sa.Integer(), nullable=True),
    sa.Column('increase_salary', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['change_department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['recipient'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['sender'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('employee', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_table('request')
    # ### end Alembic commands ###
