"""Add active field to Request table

Revision ID: f55b98ada5de
Revises: c11560165bc4
Create Date: 2021-11-20 20:00:39.090374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f55b98ada5de'
down_revision = 'c11560165bc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('active', sa.Boolean(), nullable=False, default=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'active')
    # ### end Alembic commands ###
