name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: test_db
      DB_USER: root
      DB_PASSWORD: root
      DATABASE_URL: mysql://root:root@localhost:3308/test_db
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - uses: actions/checkout@v2
      - run: |
            git fetch --prune --unshallow
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
            python-version: 3.8
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: Set up MySQL
        run: |
            sudo /etc/init.d/mysql start
            mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
            mysql -h localhost -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} test_db < db/test.sql
            mysql -e 'USE test_db; SELECT * FROM department;' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
      - name: Lauch tests
        run: |
            pytest
